[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.3"
lapin = "2.3.1"
log = "0.4.21"
tokio = { version = "1.36.0", features = ["full"] }
