name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cli/**' # Trigger only if changes are made to files under /cli directory
  pull_request:
    branches: [ "main" ]
    paths:
      - 'cli/**' # Trigger only if changes are made to files under /cli directory

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
